name: comments-download
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Add download link to product description
        env:
          WHOP_API_KEY: ${{ secrets.WHOP_API_KEY }}
          WHOP_API_VERSION: "2026-07-01"
          PRODUCT_ID: prod_0WrqduKEM3TWZ
        run: python comments/whop_add_download.py
